# Generated by Django 5.1.1 on 2024-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='author_images'),
        ),
    ]
