# Generated by Django 5.1.1 on 2024-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0002_blog_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Publish', 'Publish'), ('Recent', 'Recent'), ('Trending', 'Trending')], max_length=100),
        ),
    ]
