# Generated by Django 5.1.1 on 2024-09-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_blog_featured_image_alter_blog_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Publish', 'Publish'), ('Trending', 'Trending')], max_length=100),
        ),
    ]
