# Generated by Django 5.1.1 on 2024-09-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_alter_blog_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='introduction',
        ),
    ]
