# Generated by Django 5.1.1 on 2024-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0005_rename_content_blog_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image1',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images'),
        ),
    ]
