# Generated by Django 5.1.1 on 2024-09-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_blog_featured_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='featured_image1',
        ),
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
