# Generated by Django 5.1.1 on 2024-09-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_blog_featured_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured_image3',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images'),
        ),
    ]
