# Generated by Django 5.1.1 on 2024-09-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_blog_featured_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featured_image3',
            new_name='featured_image2',
        ),
    ]
