# Generated by Django 5.1.1 on 2024-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0010_rename_featured_image3_blog_featured_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
