# Generated by Django 5.1.1 on 2024-09-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0011_blog_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Conclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
