# Generated by Django 5.1.1 on 2024-09-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0012_blog_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Recent', 'Recent'), ('popular', 'popular'), ('Trending', 'Trending')], max_length=100),
        ),
    ]
