# Generated by Django 5.1.1 on 2024-09-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0014_blog_heading1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='heading2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
