# Generated by Django 5.1.1 on 2024-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0015_blog_heading2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authorname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
