# Generated by Django 5.1.1 on 2024-09-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
